### ISSUE TITLE
Failed to make request to Figma API: Headers is not defined

### ISSUE THREAD

**Issue by 1159733927** [GLips/Figma-Context-MCP#193]
**Describe the bug**
Failed to make request to Figma API: Headers is not defined

**Software Versions**
node:
- Figma Developer MCP: Run the MCP with `--version`—either npx or locally, depending on how you're running it.
- Node.js: v16.20.2
- NPM: 8.19.4
- Operating System: macos 13.4 
- Client: Cursor
- Client Version:版本: 1.2.4 (Universal)

**To Reproduce**

<img width="363" height="188" alt="Image" src="https://github.com/user-attachments/assets/45d14736-b12a-42b8-82b1-bc2a54f2d386" />

**Expected behavior**
   curl -H "X-Figma-Token: figd_A6J1mRhL--YB8GiKiqHr" \
   "https://api.figma.com/v1/files/v71ioWVGcnqcWm9YA1jLg9"

<img width="766" height="690" alt="Image" src="https://github.com/user-attachments/assets/932069d3-d8eb-4fc5-a0a7-615943b1fea7" />
I obtained the JSON file using curl
But I use figma-developer-mcp prompt 
Error fetching file: Failed to make request to Figma API: Headers is not defined

**Screenshots**
If applicable, add screenshots to help explain your problem. Often a screenshot of your entire chat window where you're trying to trigger the MCP is helpful.

**Server Configuration**
Provide your MCP JSON configuration, if applicable. E.g.

<img width="645" height="361" alt="Image" src="https://github.com/user-attachments/assets/5cac485a-eecb-4356-b503-8765a1d660d1" />

```

**Command Line Logs**
If you're running the MCP locally on the command line, include all the logs for those like so:

```
> npx figma-developer-mcp --figma-api-key=REDACTED

Configuration:
- FIGMA_API_KEY: ****8pXg (source: cli)
- PORT: 3333 (source: default)

Initializing Figma MCP Server in HTTP mode on port 3333...
HTTP server listening on port 3333
SSE endpoint available at http://localhost:3333/sse
Message endpoint available at http://localhost:3333/messages
New SSE connection established
```

**MCP Logs**
If you're running the MCP in a code editor like Cursor, there are MCP-specific logs that provide more context on any errors. In Cursor, you can find them by clicking `CMD + Shift + P` and looking for `Developer: Show Logs...`. Within the show logs window, you can find `Cursor MCP`—copy and paste the contents there into the bug report.

```
2025-03-18 11:36:22.251 [info] pnpx: Handling CreateClient action
2025-03-18 11:36:22.251 [info] pnpx: getOrCreateClient for stdio server.  process.platform: darwin isElectron: true
2025-03-18 11:36:22.251 [info] pnpx: Starting new stdio process with command: pnpx figma-developer-mcp --figma-api-key=REDACTED --stdio
2025-03-18 11:36:23.987 [info] pnpx: Successfully connected to stdio server
2025-03-18 11:36:23.987 [info] pnpx: Storing stdio client
2025-03-18 11:36:23.988 [info]  MCP: Handling ListOfferings action
2025-03-18 11:36:23.988 [error]  MCP: No server info found
2025-03-18 11:36:23.988 [info] pnpx: Handling ListOfferings action
2025-03-18 11:36:23.988 [info] pnpx: Listing offerings
2025-03-18 11:36:23.988 [info] pnpx: getOrCreateClient for stdio server.  process.platform: darwin isElectron: true
2025-03-18 11:36:23.988 [info] pnpx: Reusing existing stdio client
2025-03-18 11:36:23.988 [info] pnpx: Connected to stdio server, fetching offerings
2025-03-18 11:36:24.005 [info] listOfferings: Found 2 tools
2025-03-18 11:36:24.005 [info] pnpx: Found 2 tools, 0 resources, and 0 resource templates
2025-03-18 11:36:24.005 [info]  npx: Handling ListOfferings action
2025-03-18 11:36:24.005 [error]  npx: No server info found
```

**Additional context**
Add any other context about the problem here.

**Comment by GLips** [comment]
You'll need to use NodeJS version 18 or higher. The `Headers` error only happens when we fall back to a `curl` command instead of `fetch`, since `fetch` exists in NodeJS >18.

**Comment by GLips** [comment]
Oh, also, I think you might be using an older version of the Figma MCP server. We've removed `Headers` from the latest version because this error was cropping up.

Upgrading the MCP server should resolve the issue.

**Comment by 1159733927** [comment]
> 您需要使用 NodeJS 18 或更高版本。`Headers`只有当我们回退到`curl`命令而不是 时才会发生此错误`fetch`，因为`fetch`NodeJS 18 及以上版本中存在 。

I have upgraded node to v20.19.3, but the issue still persists

**Comment by GLips** [comment]
Hmm. Depends on where you're using the MCP. Most places you install it should automatically update it if you're using it via `npx`.

If you cloned the repo and run it locally, try `git pull`?
